(() => {
  'use strict';
  const OCR_ENDPOINT='/api/ocr';
  let cameraStream=null,isScanning=false,lastSpeechText='';
  const $=id=>document.getElementById(id);
  const screenStart=$('screen-start'),screenCamera=$('screen-camera'),video=$('camera-video');
  const capCanvas=$('capture-canvas'),capCtx=capCanvas.getContext('2d',{willReadFrequently:true});
  const freezeCanvas=$('freeze-canvas'),freezeCtx=freezeCanvas.getContext('2d');
  const btnStart=$('btn-start'),btnBack=$('btn-back'),btnScan=$('btn-scan'),btnSpeak=$('btn-speak'),btnAgain=$('btn-again');
  const statusBadge=$('status-badge'),scanFrameWrap=$('scan-frame-wrap'),scanFrame=$('scan-frame'),scanLine=$('scan-line');
  const progressWrap=$('progress-wrap'),progressBar=$('progress-bar'),resultPanel=$('result-panel'),resultLabel=$('result-label'),resultText=$('result-text');
  const loadingOverlay=$('loading-overlay'),loadingText=$('loading-text');
  btnStart.addEventListener('click',startCamera); btnBack.addEventListener('click',exitCamera); btnScan.addEventListener('click',scanText); btnSpeak.addEventListener('click',speakResult); btnAgain.addEventListener('click',scanAgain);
  async function startCamera(){btnStart.disabled=true;btnStart.textContent='⏳ Starting…';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera is not supported on this browser.');try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});}catch{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});}video.srcObject=cameraStream;await new Promise(r=>video.onloadedmetadata=r);await video.play();screenStart.classList.add('hidden');screenCamera.classList.remove('hidden');setStatus('ready','READY');}catch(err){console.error(err);alert(err.name==='NotAllowedError'?'Camera permission denied. Please allow access.':err.message||'Could not access camera.');btnStart.disabled=false;btnStart.textContent='📷 Start Camera';}}
  function exitCamera(){stopCamera();stopSpeech();resetResult();screenCamera.classList.add('hidden');screenStart.classList.remove('hidden');btnStart.disabled=false;btnStart.textContent='📷 Start Camera';}
  function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;}video.pause();video.srcObject=null;hideFreeze();}
  async function scanText(){if(isScanning)return;isScanning=true;resetResult();btnScan.disabled=true;scanLine.classList.add('active');progressWrap.classList.remove('hidden');progressBar.style.width='8%';setStatus('reading','CAPTURING');showLoading('Capturing image…');try{const imageBase64=captureScanFrame();if(!imageBase64)throw new Error('Camera is not ready. Try again.');showFreeze();setStatus('reading','READING');showLoading('Reading text with AWS Rekognition…');progressBar.style.width='35%';const res=await fetch(OCR_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageBase64})});progressBar.style.width='75%';const json=await res.json().catch(()=>({}));if(!res.ok||!json.ok)throw new Error(json.error||`OCR request failed (${res.status})`);const cleaned=filterOcrLines(json.lines||[],json.text||'');progressBar.style.width='100%';if(!cleaned)showError('No readable English text found. Try again.');else showResult(cleaned);}catch(err){console.error(err);showError(err.message||'Scan failed. Please try again.');}finally{isScanning=false;btnScan.disabled=false;scanLine.classList.remove('active');hideLoading();setTimeout(()=>{progressWrap.classList.add('hidden');progressBar.style.width='0%';},550);}}
  function captureScanFrame(){const vw=video.videoWidth,vh=video.videoHeight;if(!vw||!vh)return'';const v=video.getBoundingClientRect(),f=scanFrame.getBoundingClientRect();const videoAspect=vw/vh,elementAspect=v.width/v.height;let displayedW,displayedH,offsetX,offsetY;if(videoAspect>elementAspect){displayedH=v.height;displayedW=displayedH*videoAspect;offsetX=(displayedW-v.width)/2;offsetY=0;}else{displayedW=v.width;displayedH=displayedW/videoAspect;offsetX=0;offsetY=(displayedH-v.height)/2;}const left=f.left-v.left+offsetX,top=f.top-v.top+offsetY;let cropX=(left/displayedW)*vw,cropY=(top/displayedH)*vh,cropW=(f.width/displayedW)*vw,cropH=(f.height/displayedH)*vh;const padX=cropW*.08,padY=cropH*.12;cropX=clamp(cropX-padX,0,vw-1);cropY=clamp(cropY-padY,0,vh-1);cropW=clamp(cropW+padX*2,1,vw-cropX);cropH=clamp(cropH+padY*2,1,vh-cropY);const targetW=Math.min(1280,Math.max(900,cropW)),scale=targetW/cropW,outW=Math.round(cropW*scale),outH=Math.round(cropH*scale);capCanvas.width=outW;capCanvas.height=outH;capCtx.imageSmoothingEnabled=true;capCtx.imageSmoothingQuality='high';capCtx.drawImage(video,cropX,cropY,cropW,cropH,0,0,outW,outH);return capCanvas.toDataURL('image/jpeg',.82).split(',')[1];}
  function showFreeze(){const r=video.getBoundingClientRect();freezeCanvas.width=r.width*devicePixelRatio;freezeCanvas.height=r.height*devicePixelRatio;freezeCanvas.style.width=r.width+'px';freezeCanvas.style.height=r.height+'px';freezeCtx.save();freezeCtx.scale(devicePixelRatio,devicePixelRatio);freezeCtx.drawImage(video,0,0,r.width,r.height);freezeCtx.restore();freezeCanvas.classList.add('show');}
  function hideFreeze(){freezeCanvas.classList.remove('show');}
  function filterOcrLines(lines,fallback=''){const arr=Array.isArray(lines)&&lines.length?lines.map(x=>typeof x==='string'?x:x.text||''):String(fallback).split(/
+/);const out=[],seen=new Set();for(const raw of arr){const line=cleanLine(raw);if(!isGoodLine(line))continue;const key=line.toLowerCase().replace(/[^a-z0-9]+/g,'');if(!key||seen.has(key))continue;seen.add(key);out.push(line);if(out.length>=8)break;}return out.join('
').trim();}
  function cleanLine(t){return String(t||'').replace(/[|_[\]{}<>~^`•·]/g,' ').replace(/[^A-Za-z0-9 .,%+\-&/():]/g,' ').replace(/\s{2,}/g,' ').trim();}
  function isGoodLine(line){if(!line||line.length<3||line.length>85)return false;const letters=(line.match(/[A-Za-z]/g)||[]).length,digits=(line.match(/[0-9]/g)||[]).length,chars=line.replace(/\s/g,'').length;if(letters<2||!chars)return false;const ratio=letters/chars;if(ratio<.35)return false;if(digits>=6&&ratio<.55)return false;if(/^[0-9\s.,:/+\-%]+$/.test(line))return false;if(/^(www|http|https)/i.test(line))return false;if(/^[A-Za-z]{1,2}$/.test(line))return false;return true;}
  function showResult(text){lastSpeechText=buildSpeechText(text);resultLabel.textContent='TEXT FOUND';resultLabel.style.color='var(--violet)';resultText.textContent=text;resultText.classList.remove('error');resultPanel.classList.add('show');btnScan.classList.add('hidden');scanFrameWrap.classList.add('hidden');setStatus('done','DONE');navigator.vibrate?.([40,30,80]);speakResult();}
  function showError(msg){lastSpeechText='';resultLabel.textContent='RESULT';resultLabel.style.color='var(--pink)';resultText.textContent=msg||'No readable English text found. Try again.';resultText.classList.add('error');resultPanel.classList.add('show');btnScan.classList.add('hidden');setStatus('error','NOT FOUND');btnSpeak.disabled=true;navigator.vibrate?.([50,50,50]);}
  async function scanAgain(){stopSpeech();hideFreeze();resetResult();if(video.paused&&cameraStream){try{await video.play();}catch{}}}
  function resetResult(){resultPanel.classList.remove('show');resultText.classList.remove('error');resultText.textContent='';btnScan.classList.remove('hidden');btnSpeak.disabled=false;btnSpeak.classList.remove('speaking');scanFrameWrap.classList.remove('hidden');setStatus('ready','READY');}
  function speakResult(){if(!lastSpeechText||!('speechSynthesis'in window))return;stopSpeech();const u=new SpeechSynthesisUtterance(lastSpeechText);u.lang='en-US';u.rate=.86;u.pitch=1;const voices=speechSynthesis.getVoices();const voice=voices.find(v=>v.lang==='en-US'&&v.localService)||voices.find(v=>v.lang&&v.lang.startsWith('en'));if(voice)u.voice=voice;btnSpeak.classList.add('speaking');u.onend=u.onerror=()=>btnSpeak.classList.remove('speaking');speechSynthesis.speak(u);}
  function buildSpeechText(t){return String(t||'').replace(/[^\w\s.,%+\-&/():]/g,' ').replace(/\s+/g,' ').trim().slice(0,360);}
  function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();btnSpeak.classList.remove('speaking');}
  function setStatus(type,text){statusBadge.className=`status ${type}`;statusBadge.textContent=text;}
  function showLoading(t){loadingText.textContent=t;loadingOverlay.classList.remove('hidden');}function hideLoading(){loadingOverlay.classList.add('hidden');}
  function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
  if('speechSynthesis'in window){speechSynthesis.getVoices();speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices();}
  window.addEventListener('pagehide',stopCamera);window.addEventListener('beforeunload',stopCamera);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSpeech();});
})();
